const C=window.STOCKFLOW_SUPABASE||{}, DB='stockflow_local', VER=4, PS='products', SS='sales', QS='sync_queue';
let db,supabase,currentUser,currentView='dashboard',authMode='login',realtimeChannel=null,realtimeTimer=null,authBooting=false;
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function toast(m,type='ok'){let t=$('#toast');if(!t){t=document.createElement('div');t.id='toast';t.className='toast';document.body.append(t)}t.textContent=m;t.dataset.type=type;t.classList.add('show');clearTimeout(t._t);t._t=setTimeout(()=>t.classList.remove('show'),2800)}
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open(DB,VER);r.onupgradeneeded=e=>{let d=e.target.result;if(!d.objectStoreNames.contains(PS))d.createObjectStore(PS,{keyPath:'id'});if(!d.objectStoreNames.contains(SS))d.createObjectStore(SS,{keyPath:'id'});if(!d.objectStoreNames.contains(QS))d.createObjectStore(QS,{keyPath:'id',autoIncrement:true})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function st(n,m='readonly'){return db.transaction(n,m).objectStore(n)}
const all=n=>new Promise((r,j)=>{let q=st(n).getAll();q.onsuccess=()=>r(q.result||[]);q.onerror=()=>j(q.error)});
const put=(n,v)=>new Promise((r,j)=>{let q=st(n,'readwrite').put(v);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});
const add=(n,v)=>new Promise((r,j)=>{let q=st(n,'readwrite').add(v);q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)});
const del=(n,id)=>new Promise((r,j)=>{let q=st(n,'readwrite').delete(id);q.onsuccess=()=>r();q.onerror=()=>j(q.error)});
const stock=p=>(p.colours||[]).reduce((a,c)=>a+Object.values(c.sizes||{}).reduce((x,q)=>x+Number(q||0),0),0);
const money=n=>`৳${Number(n||0).toLocaleString('en-BD',{maximumFractionDigits:2})}`;
function closeModal(){let m=$('#modal');if(m){m.classList.remove('show');m.innerHTML=''}}
function modal(h){let m=$('#modal');m.innerHTML=`<div class="modal-box">${h}</div>`;m.classList.add('show');m.onclick=e=>{if(e.target===m)closeModal()};m.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeModal)}
function ready(){return C.url&&!C.url.includes('YOUR_PROJECT')&&C.publishableKey&&!C.publishableKey.includes('YOUR_')}
function showAuth(message=''){let a=$('#authScreen');a.style.display='flex';$('#appShell').style.display='none';$('#authTitle').textContent=authMode==='login'?'Welcome back':'Create your account';$('#authSubtitle').textContent=authMode==='login'?'Sign in to access your inventory.':'Create an account to sync inventory across phones.';$('#authSubmit').textContent=authMode==='login'?'Sign In':'Create Account';$('#authConfirmWrap').style.display=authMode==='login'?'none':'block';$('#authSwitch').textContent=authMode==='login'?'Create an account':'Already have an account? Sign in';$('#authMessage').textContent=message}
async function authSubmit(e){e.preventDefault();if(!supabase)return;let email=$('#authEmail').value.trim(),password=$('#authPassword').value,btn=$('#authSubmit');btn.disabled=true;$('#authMessage').textContent='';try{if(authMode==='login'){let {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;$('#authMessage').textContent='Signing in…'}else{if(password!==$('#authConfirm').value)throw Error('Passwords do not match.');let {data,error}=await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;if(data.session){$('#authMessage').textContent='Account created. Signing you in…'}else{$('#authMessage').textContent='Account created. Please check your email to confirm your account, then sign in.'}}}catch(e){console.error('Auth error',e);$('#authMessage').textContent=e.message||'Authentication failed.'}finally{btn.disabled=false}}
async function auth(){if(!ready()){showAuth('Supabase setup is missing. Add your Project URL and Publishable Key to config.js.');return}if(!window.supabase?.createClient)throw Error('Supabase library failed to load. Check your internet connection and refresh.');supabase=window.supabase.createClient(C.url,C.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});supabase.auth.onAuthStateChange((event,session)=>{setTimeout(async()=>{try{if(event==='INITIAL_SESSION'){if(session)await signedIn(session.user);else showAuth();return}if(event==='SIGNED_IN'&&session){await signedIn(session.user);return}if(event==='SIGNED_OUT'){await signedOut();}}catch(e){console.error('Auth state error',e);showAuth(e.message||'Authentication error.')}},0)});}
function normalizeP(p){return {...p,id:p.id,name:p.name,colours:p.colours||[],createdAt:p.created_at,updatedAt:p.updated_at}}
function normalizeS(s){return {...s,id:s.id,productId:s.product_id,productName:s.product_name,colour:s.colour,size:s.size,quantity:Number(s.quantity),price:Number(s.price),total:Number(s.total),date:s.date}}
async function cloudP(p){let {error}=await supabase.from('products').upsert({id:p.id,user_id:currentUser.id,name:p.name,colours:p.colours,created_at:p.createdAt||new Date().toISOString(),updated_at:new Date().toISOString()});if(error)throw error}
async function cloudS(s){let {error}=await supabase.from('sales').upsert({id:s.id,user_id:currentUser.id,product_id:s.productId,product_name:s.productName,colour:s.colour,size:s.size,quantity:s.quantity,price:s.price,total:s.total,date:s.date});if(error)throw error}
async function queue(op,payload){await add(QS,{op,payload})}
async function saveP(p){await put(PS,p);try{await cloudP(p)}catch(e){await queue('product',p);throw e}}
async function saveS(s){await put(SS,s);try{await cloudS(s)}catch(e){await queue('sale_legacy',s);throw e}}
async function recordCloudSale(s){let {data,error}=await supabase.rpc('record_stock_sale',{p_id:s.id,p_product_id:s.productId,p_colour:s.colour,p_size:s.size,p_quantity:s.quantity,p_price:s.price});if(error)throw error;return data}
async function sync(){if(!supabase||!currentUser||!navigator.onLine)return;try{let {data:p,error:a}=await supabase.from('products').select('*').eq('user_id',currentUser.id);if(a)throw a;let {data:s,error:b}=await supabase.from('sales').select('*').eq('user_id',currentUser.id).order('date',{ascending:false});if(b)throw b;for(let x of p||[])await put(PS,normalizeP(x));for(let x of s||[])await put(SS,normalizeS(x));await flushQueue()}catch(e){console.warn('Sync:',e.message||e);toast('Cloud sync unavailable. Local data is safe.','error')}}
async function flushQueue(){let q=await all(QS);for(let x of q){try{if(x.op==='product')await cloudP(x.payload);else if(x.op==='sale')await recordCloudSale(x.payload);await del(QS,x.id)}catch(e){console.warn('Pending sync failed:',e.message||e)}}}
function setupRealtime(){if(!supabase||!currentUser)return;if(realtimeChannel){supabase.removeChannel(realtimeChannel);realtimeChannel=null}realtimeChannel=supabase.channel('stockflow-user-'+currentUser.id).on('postgres_changes',{event:'*',schema:'public',table:'products',filter:'user_id=eq.'+currentUser.id},payload=>{if(payload.eventType==='DELETE')del(PS,payload.old.id).catch(console.error);else put(PS,normalizeP(payload.new)).catch(console.error);scheduleRealtimeRender()}).on('postgres_changes',{event:'*',schema:'public',table:'sales',filter:'user_id=eq.'+currentUser.id},payload=>{if(payload.eventType!=='DELETE')put(SS,normalizeS(payload.new)).catch(console.error);scheduleRealtimeRender()}).subscribe(status=>console.log('StockFlow Realtime:',status))}
function scheduleRealtimeRender(){clearTimeout(realtimeTimer);realtimeTimer=setTimeout(()=>render().catch(console.error),180)}
async function signedIn(u){if(!u||currentUser?.id===u.id&&document.querySelector('#appShell').style.display==='block')return;currentUser=u;$('#authScreen').style.display='none';$('#appShell').style.display='block';$('#userEmail').textContent=u.email||'';setupNav();await sync();setupRealtime();await render()}
async function signedOut(){if(realtimeChannel){await supabase.removeChannel(realtimeChannel);realtimeChannel=null}currentUser=null;$('#appShell').style.display='none';showAuth()}
const sizes=['XS','S','M','L','XL','XXL'];
const crow=c=>`<div class="colour-row"><div class="colour-row-head"><input class="colour-name" placeholder="Colour name" value="${esc(c.name||'')}"><button type="button" class="danger-text remove-colour">Remove</button></div><div class="size-grid">${sizes.map(s=>`<label><span>${s}</span><input class="size-qty" data-size="${s}" type="number" min="0" value="${Number(c.sizes?.[s]||0)}"></label>`).join('')}</div></div>`;
function openProduct(old=null){modal(`<div class="modal-head"><div><h2>${old?'Edit Product':'Add Product'}</h2><p>Synced to your Supabase account.</p></div><button class="icon-btn" data-close>×</button></div><form id="pf"><label class="field"><span>Product name</span><input id="pn" required value="${esc(old?.name||'')}"></label><div class="section-title"><span>Colours & sizes</span><button type="button" class="secondary" id="ac">+ Add Colour</button></div><div id="cr">${(old?.colours?.length?old.colours:[{}]).map(crow).join('')}</div><div class="modal-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary" id="sp">Save Product</button></div></form>`);$('#ac').onclick=()=>$('#cr').insertAdjacentHTML('beforeend',crow({}));$('#cr').onclick=e=>{if(e.target.classList.contains('remove-colour')){let r=$('#cr').children;if(r.length>1)e.target.closest('.colour-row').remove();else toast('At least one colour is required.','error')}};$('#pf').onsubmit=async e=>{e.preventDefault();let b=$('#sp');b.disabled=true;try{let name=$('#pn').value.trim(),cs=[...$('#cr').querySelectorAll('.colour-row')].map(r=>{let z={};r.querySelectorAll('.size-qty').forEach(i=>z[i.dataset.size]=Math.max(0,Number(i.value||0)));return{name:r.querySelector('.colour-name').value.trim(),sizes:z}});if(!name)throw Error('Product name is required.');if(cs.some(c=>!c.name))throw Error('Every colour needs a name.');if(!cs.some(c=>stock({colours:[c]})>0))throw Error('Enter at least one quantity.');let p={...(old||{}),id:old?.id||crypto.randomUUID(),name,colours:cs,createdAt:old?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};try{await saveP(p);toast('Product saved to cloud.')}catch(x){toast('Saved locally; cloud sync pending.','error')}closeModal();await renderInventory()}catch(x){toast(x.message,'error')}finally{b.disabled=false}}}
async function sell(p){modal(`<div class="modal-head"><div><h2>Record Sale</h2><p>${esc(p.name)}</p></div><button class="icon-btn" data-close>×</button></div><form id="sf"><label class="field"><span>Colour</span><select id="sc">${p.colours.map((c,i)=>`<option value="${i}">${esc(c.name)}</option>`).join('')}</select></label><label class="field"><span>Size</span><select id="ssz"></select></label><div id="av" class="muted"></div><label class="field"><span>Quantity</span><input id="sq" type="number" min="1" value="1"></label><label class="field"><span>Sale price per item</span><input id="spr" type="number" min="0" step=".01" required></label><div class="modal-actions"><button type="button" class="secondary" data-close>Cancel</button><button class="primary">Save Sale</button></div></form>`);function upd(){let c=p.colours[+$('#sc').value];$('#ssz').innerHTML=sizes.map(s=>`<option value="${s}" ${+(c.sizes?.[s]||0)<=0?'disabled':''}>${s} — ${+(c.sizes?.[s]||0)} available</option>`).join('');let a=+(c.sizes?.[$('#ssz').value]||0);$('#av').textContent=`Available: ${a}`;$('#sq').max=a}$('#sc').onchange=upd;$('#ssz').onchange=upd;$('#sf').onsubmit=async e=>{e.preventDefault();let b=e.submitter;b.disabled=true;try{let c=p.colours[+$('#sc').value],size=$('#ssz').value,q=+$('#sq').value,price=+$('#spr').value,a=+(c?.sizes?.[size]||0);if(!c||!size||q<1||q>a)throw Error('Invalid quantity or insufficient stock.');if(price<0)throw Error('Enter a valid price.');c.sizes[size]=a-q;let s={id:crypto.randomUUID(),productId:p.id,productName:p.name,colour:c.name,size,quantity:q,price,total:q*price,date:new Date().toISOString()};await put(PS,p);await put(SS,s);try{await recordCloudSale(s);toast('Sale saved and synced.')}catch(x){await queue('sale',s);toast('Sale saved locally; cloud sync pending.','error')}closeModal();await renderInventory()}catch(x){toast(x.message,'error')}finally{b.disabled=false}};upd()}
async function renderDashboard(){let p=await all(PS),s=await all(SS),d=new Date().toISOString().slice(0,10),t=s.filter(x=>x.date.slice(0,10)===d);$('#content').innerHTML=`<div class="page-title"><div><h1>Dashboard</h1><p>Shared cloud inventory.</p></div></div><div class="stats"><div class="stat-card"><span>Products</span><strong>${p.length}</strong></div><div class="stat-card"><span>Available Stock</span><strong>${p.reduce((a,x)=>a+stock(x),0)}</strong></div><div class="stat-card"><span>Today's Units Sold</span><strong>${t.reduce((a,x)=>a+x.quantity,0)}</strong></div><div class="stat-card"><span>Today's Revenue</span><strong>${money(t.reduce((a,x)=>a+x.total,0))}</strong></div></div><div class="card"><h3>Sync</h3><p class="muted">${navigator.onLine?'Online — cloud sync active.':'Offline — local changes will sync when internet returns.'}</p><button class="primary" id="da">+ Add Product</button></div>`;$('#da').onclick=()=>openProduct()}
async function renderInventory(){let p=await all(PS);$('#content').innerHTML=`<div class="page-title"><div><h1>Inventory</h1><p>Shared across your signed-in phones.</p></div><button class="primary" id="ia">+ Add Product</button></div><div class="search-row"><input id="iq" placeholder="Search products…"></div><div id="pl"></div>`;$('#ia').onclick=()=>openProduct();function draw(q=''){let f=p.filter(x=>x.name.toLowerCase().includes(q.toLowerCase()));$('#pl').innerHTML=f.length?f.map(x=>`<div class="product-card card"><div class="product-card-head"><div><h3>${esc(x.name)}</h3><span>${stock(x)} available</span></div><div class="actions"><button class="secondary ed" data-id="${x.id}">Edit</button><button class="primary sl" data-id="${x.id}">Sell</button></div></div><div class="colour-list">${x.colours.map(c=>`<div class="colour-block"><strong>${esc(c.name)}</strong><div class="size-chips">${sizes.map(s=>`<span>${s}: <b>${+(c.sizes?.[s]||0)}</b></span>`).join('')}</div></div>`).join('')}</div></div>`).join(''):`<div class="empty card"><h3>No products</h3><p>Add your first product.</p></div>`;$('#pl').querySelectorAll('.ed').forEach(b=>b.onclick=()=>openProduct(p.find(x=>x.id===b.dataset.id)));$('#pl').querySelectorAll('.sl').forEach(b=>b.onclick=()=>sell(p.find(x=>x.id===b.dataset.id)))}$('#iq').oninput=e=>draw(e.target.value);draw()}
async function renderSales(){let s=(await all(SS)).sort((a,b)=>new Date(b.date)-new Date(a.date));$('#content').innerHTML=`<div class="page-title"><div><h1>Sales History</h1><p>Sales synced to your account.</p></div></div><div class="card table-wrap"><table><thead><tr><th>Date</th><th>Product</th><th>Colour</th><th>Size</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead><tbody>${s.map(x=>`<tr><td>${new Date(x.date).toLocaleString()}</td><td>${esc(x.productName)}</td><td>${esc(x.colour)}</td><td>${x.size}</td><td>${x.quantity}</td><td>${money(x.price)}</td><td>${money(x.total)}</td></tr>`).join('')||'<tr><td colspan="7">No sales yet.</td></tr>'}</tbody></table></div>`}
async function renderReports(){let s=await all(SS),g={};s.forEach(x=>{g[x.productName]??={u:0,r:0};g[x.productName].u+=x.quantity;g[x.productName].r+=x.total});$('#content').innerHTML=`<div class="page-title"><div><h1>Reports</h1><p>Sales performance.</p></div></div><div class="card table-wrap"><table><thead><tr><th>Product</th><th>Units</th><th>Revenue</th></tr></thead><tbody>${Object.entries(g).map(([n,v])=>`<tr><td>${esc(n)}</td><td>${v.u}</td><td>${money(v.r)}</td></tr>`).join('')||'<tr><td colspan="3">No sales data.</td></tr>'}</tbody></table></div>`}
async function renderSettings(){$('#content').innerHTML=`<div class="page-title"><div><h1>Settings</h1><p>Account and cloud sync.</p></div></div><div class="card"><h3>Account</h3><p>${esc(currentUser.email)}</p><button class="secondary" id="lo">Sign Out</button></div><div class="card"><h3>Synchronization</h3><p class="muted">Data is stored in Supabase and cached locally for offline use.</p><button class="primary" id="sn">Sync Now</button></div>`;$('#lo').onclick=()=>supabase.auth.signOut();$('#sn').onclick=async()=>{await sync();toast('Sync completed.');await render()}}
async function render(){if(currentView==='dashboard')return renderDashboard();if(currentView==='inventory')return renderInventory();if(currentView==='sales')return renderSales();if(currentView==='reports')return renderReports();return renderSettings()}
function setupNav(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=async()=>{currentView=b.dataset.page;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x===b));await render()});$('#addTop')?.addEventListener('click',()=>openProduct())}
async function init(){try{await openDB();$('#authForm').onsubmit=authSubmit;$('#authSwitch').onclick=()=>{authMode=authMode==='login'?'signup':'login';showAuth()};await auth()}catch(e){console.error(e);toast(e.message||'Startup error','error')}}
addEventListener('online',()=>sync().then(()=>render()).catch(console.error));addEventListener('DOMContentLoaded',init);
